version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:29092"
#HOST PORT:CONTAINER_PORT
    environment:
      #broker unique identifier
      KAFKA_NODE_ID: 1

      #Kafka KRaft mode introduces  2 roles - broker that handles producer/consumer requests, replication
      #controller - manage the cluster meta data
      KAFKA_PROCESS_ROLES: broker, controller

      #KAFKA listen for the connection on this: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093


#      client sabse pehle bootstrap server se connect hota hai
#      fir kafka bolta hai ki mujhe address par use karo and ye address KAFKA_ADVERTISED_LISTENERS se aata hai

#what does kafka tell client to use
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      #Left ones are listeners
      #Right ones are protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

# Kraft mode mein zookeeper ka replacement hai ye
      #'1' is node id
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    #jo bhi data /var/lib/kafka/data ismein hoga vo store hojaega temporary memory mein kafka-data mein locally
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest # this will create a ui for us
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "7575:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - kafka-net

networks:
  kafka-net:

volumes:
  kafka-data:

  #COmmands

  # docker compose up -d
  # to start the apache container in docker

  # docker compose down
  #to remove the apache container in docker
