spring.application.name=PRODUCT-SERVICE


spring.profiles.active=dev

# we need spring config client dependency in all
#microservices so that each service can connect with spring config server

#this property comes from spring cloud config client
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}